In [1]:
import numpy as np
from math import factorial
def combinations(n, k):
    return int(factorial(n) / (factorial(k) * factorial(n - k)))
def arrangements(n, k):
    return int(factorial(n) / factorial(n - k))
def permutations(n):
    return int(factorial(n))
combinations(36, 4)

58905

1) Известно, что генеральная совокупность распределена нормально
со средним квадратическим отклонением, равным 16.
Найти доверительный интервал для оценки математического ожидания a с надежностью 0.95,
если выборочная средняя M = 80, а объем выборки n = 256.

In [2]:
std1 = 16
n1=256
M1=80
a1=0.95
##(p-a)/2 = 1.96 - по таблице
p1=1.96
### Решение:
nig_gran = M1-p1*(std1/(n1**0.5))
verh_gran = M1+p1*(std1/(n1**0.5))
nig_gran


78.04

In [3]:
verh_gran

81.96

2) В результате 10 независимых измерений некоторой величины X, выполненных с одинаковой точностью,
получены опытные данные:
6.9, 6.1, 6.2, 6.8, 7.5, 6.3, 6.4, 6.9, 6.7, 6.1
Предполагая, что результаты измерений подчинены нормальному закону распределения вероятностей,
оценить истинное значение величины X при помощи доверительного интервала, покрывающего это
значение с доверительной вероятностью 0,95.

In [4]:
arr = np.array([6.9, 6.1, 6.2, 6.8, 7.5, 6.3, 6.4, 6.9, 6.7, 6.1])
arr

array([6.9, 6.1, 6.2, 6.8, 7.5, 6.3, 6.4, 6.9, 6.7, 6.1])

In [5]:
arr.sort()
arr

array([6.1, 6.1, 6.2, 6.3, 6.4, 6.7, 6.8, 6.9, 6.9, 7.5])

In [6]:
mean = arr.mean()
mean

6.590000000000001

In [10]:
S_smesh=np.std(arr, ddof=1)
S_smesh

0.4508017549014448

In [12]:
### Используем T критерий так как сигма не известна
n2 = 10
mean = 6.59
### P = 2.262 по таблице для T критерия и 95% интервала 
p2 = 2.262
### Решение 
nig_gran_2 = mean - (p2*(S_smesh/(n2**0.5)))
verh_gran_2 = mean + (p2*(S_smesh/(n2**0.5)))
nig_gran_2

6.2675382559124255

In [13]:
verh_gran_2

6.912461744087574

3.) Утверждается, что шарики для подшипников, изготовленные автоматическим станком, имеют средний диаметр 17 мм.
Используя односторонний критерий с α=0,05, проверить эту гипотезу, если в выборке из n=100 шариков средний диаметр
оказался равным 17.5 мм, а дисперсия известна и равна 4 кв.мм.

In [14]:
x = 17.5
x0 = 17
std3 = 4**0.5
n = 100
### решение , P по таблице = 1,645 - односторонний критерий
z = (x-x0)/(std3/(n**0.5))
z


2.5

In [15]:
### z>p поэтому гипотеза верна 

 Продавец утверждает, что средний вес пачки печенья составляет 200 г. Из партии извлечена выборка из 10 пачек. Вес каждой пачки составляет: 202, 203, 199, 197, 195, 201, 200, 204, 194, 190. Известно, что их веса распределены нормально. Верно ли утверждение продавца, если учитывать, что доверительная вероятность равна 99%?

In [16]:
arr4 = np.array([202, 203, 199, 197, 195, 201, 200, 204, 194, 190])
arr4

array([202, 203, 199, 197, 195, 201, 200, 204, 194, 190])

In [17]:
arr4.sort()
arr4

array([190, 194, 195, 197, 199, 200, 201, 202, 203, 204])

In [18]:
mean4 = arr4.mean()
mean4

198.5

In [19]:
S_smesh4=np.std(arr4, ddof=1)
S_smesh4

4.453463071962462

In [20]:
n = 10
#### Используюя t критерий для 99% доверительный интервал = 3,25 по таблице для T критерия 
z_nig = mean4 - (3.25*(S_smesh4/(n**0.5)))
z_verh = mean4 + (3.25*(S_smesh4/(n**0.5)))
z_nig 

193.9229967955732

In [21]:
z_verh

203.0770032044268

In [25]:
Z = (mean4-200)/(S_smesh4/(n**0.5))
Z

-1.0651074037450896

In [26]:
### ОТВЕТ: поскольку доверительный интервал по таблице для T критерия = 3,25 а расчетный интервад - 1,065, то есть менее чем 
### значение по таблице то утверждение продавца не верно