In [1]:
import numpy as np
from math import factorial
def combinations(n, k):
    return int(factorial(n) / (factorial(k) * factorial(n - k)))
def arrangements(n, k):
    return int(factorial(n) / factorial(n - k))
def permutations(n):
    return int(factorial(n))
combinations(36, 4)

58905

# Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [5]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [17]:
#Расчет ковариации в ручном режиме: 
cov_hand = np.mean(ks*zp)-np.mean(ks)*np.mean(zp)
cov_hand
### Значение равно значению рассчитанному ниже

9157.839999999997

In [6]:
np.corrcoef(zp,ks)
#### Полученное значение равно значениям полученным через ковариацию(расчет ниже)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [7]:
np.cov(zp,ks,ddof=1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [11]:
np.cov(zp,ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [9]:
zp_std_smes = np.std(zp)
zp_std2_nesmes = np.std(zp, ddof=1)
ks_std_smes = np.std(ks)
ks_std2_nesmes = np.std(ks, ddof=1)

In [14]:
cpirs_nesmesh = 10175.37777778/(zp_std2_nesmes*ks_std2_nesmes)
cpirs_nesmesh

0.88749009207411

In [15]:
cpirs_smesh =  9157.84/(zp_std_smes*ks_std_smes)
cpirs_smesh

0.8874900920739162

# Измерены значения IQ выборки студентов, обучающихся в местных технических вузах: 131, 125, 115, 122, 131, 115, 107, 99, 125, 111. Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [20]:
zd3 = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
zd3.sort()
zd3

array([ 99, 107, 111, 115, 115, 122, 125, 125, 131, 131])

In [21]:
mean = zd3.mean()
mean

118.1

In [22]:
S3_smesh=np.std(zd3, ddof=1)
S3_smesh

10.54566788359614

In [23]:
### Используем T критерий так как сигма не известна
n2 = 10
mean = 118.1
### P = 2.262 по таблице для T критерия и 95% интервала 
p2 = 2.262
### Решение 
nig_gran_2 = mean - (p2*(S3_smesh/(n2**0.5)))
verh_gran_2 = mean + (p2*(S3_smesh/(n2**0.5)))
nig_gran_2

110.55660776308164

In [24]:
verh_gran_2

125.64339223691834

# Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [26]:
M1 = 174.2
std3 = 25**0.5
n1 = 27
##(p-a)/2 = 1.96 - по таблице
p1=1.96
### Решение:
nig_gran = M1-p1*(std3/(n1**0.5))
verh_gran = M1+p1*(std3/(n1**0.5))
nig_gran

172.31398912064722

In [27]:
verh_gran

176.08601087935276