In [1]:
import numpy as np
from math import factorial
def combinations(n, k):
    return int(factorial(n) / (factorial(k) * factorial(n - k)))
def arrangements(n, k):
    return int(factorial(n) / factorial(n - k))
def permutations(n):
    return int(factorial(n))
combinations(36, 4)

58905

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [4]:
# количество наблюдений
n = 10

In [5]:
b = (np.mean(zp * ks) - np.mean(zp) * np.mean(ks)) / (np.mean(zp**2) - np.mean(zp) ** 2)
b

2.620538882402765

In [22]:
a = np.mean(ks) - b * np.mean(zp)
a

444.1773573243596

In [24]:
y= 444.17+2.62*zp
y

array([535.87, 562.07, 941.97, 968.17, 548.97, 627.57, 585.65, 837.17,
       758.57, 732.37])

In [ ]:
###с использованием intercept

In [25]:
from sklearn.linear_model import LinearRegression
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110]).reshape((-1, 1))
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [26]:
print(zp)

[[ 35]
 [ 45]
 [190]
 [200]
 [ 40]
 [ 70]
 [ 54]
 [150]
 [120]
 [110]]


In [27]:
print(ks)

[401 574 874 919 459 739 653 902 746 832]


In [32]:
model = LinearRegression().fit(zp, ks)

In [33]:
print('intercept:', model.intercept_)

intercept: 444.1773573243596


In [34]:
print('slope:', model.coef_)

slope: [2.62053888]


# Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [36]:
x = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
def mse_(B1, y=y, x=x,n=10):
    return np.sum((B1*x-y)**2)/n
alpha = 1e-6
alpha

1e-06

In [37]:
B1 = 0.1
n=10
for i in range(10):
    B1-=alpha*(2/n)*np.sum((B1*x-y)*x)
    print('B1={}'.format(B1))

B1=1.06196842
B1=0.995733238803004
B1=1.0002937827221057
B1=0.9999797719432088
B1=1.0000013927785767
B1=0.9999999041019024
B1=1.0000000066029484
B1=0.9999999995453619
B1=1.0000000000313036
B1=0.9999999999978446


In [38]:
B1 = 0.1
n=10
for i in range(3000):
    B1-=alpha*(2/n)*np.sum((B1*x-y)*x)
    if i%500==0:
        print('Iteration = {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=mse_(B1)))

Iteration = 0, B1=1.06196842, mse=2052.2447635957697
Iteration = 500, B1=1.0, mse=0.0
Iteration = 1000, B1=1.0, mse=0.0
Iteration = 1500, B1=1.0, mse=0.0
Iteration = 2000, B1=1.0, mse=0.0
Iteration = 2500, B1=1.0, mse=0.0


In [40]:
mse_(1.0)

0.0

# 3. В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

Лапласа когда дисперсия или среднеквадратичное известны а T критерий стьюдента когда не известны